INSERT INTO movies(title, creationDate, releaseDate, genres, directorName, runtimeMins, summary, totalScore, totalComments)
VALUES
('Pulp Fiction', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-14',
 '{"CRIME","DRAMA"}', 'Quentin Tarantino', 154, 'The lives of two mob hit men, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 0, 0),
('Quiz Show', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-07',
 '{"DRAMA","HISTORY"}', 'Robert Redford', 133, 'A young lawyer Jim Goodwin investigates a potentially fixed game show. Charlie Van Doren, a big time show winner is under Goodwin''s investigation.', 0, 0),
('Ray Alexander: A Taste for Justice', TIMESTAMP '2014-09-10', TIMESTAMP '1994-05-13',
 '{"DRAMA","MYSTERY"}', 'Gary Nelson', 100, 'San Francisco cafe owner Ray Alexander moonlights as a detective. His new case has him looking into the murder of a psychiatrist whose wife has been framed.', 0, 0),
('La reina de la noche', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-07',
 '{"BIOGRAPHY","DRAMA"}', 'Arturo Ripstein', 117, 'A female cabaret artist has to leave Berlin, Germany, after an incident with the Nazis. Back in her fatherland Mexico she tries and succeeds in remaking her career.', 0, 0),
('Queen Margot', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-09',
 '{"BIOGRAPHY","DRAMA","HISTORY"}', 'Patrice Chéreau', 159, 'Young Queen Margot finds herself trapped in an arranged marriage amidst a religious war between Catholics and Protestants. She hopes to escape with a new lover, but finds herself imprisoned by her powerful and ruthless family.', 0, 0),
('Revenge of the Red Baron', TIMESTAMP '2014-09-10', TIMESTAMP '1994-02-16',
 '{"COMEDY","FANTASY","HORROR"}', 'Robert Gordon', 100, 'The Red Baron returns in a toy plane to kill the former World War I ace that shot him down.', 0, 0),
('The River Wild', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-30',
 '{"ACTION","ADVENTURE","CRIME"}', 'Curtis Hanson', 111, 'Rafting expert Gail takes on a pair of armed killers while navigating a spectacularly violent river.', 0, 0),
('Road to Saddle River', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-23',
 '{"COMEDY"}', 'Francis Damberger', 110, 'An East European butcher, the Cowboy Kid, heads west to find Saddle River. A comic odyssey, filled with odd characters, misadventures and stunningly beautiful western landscapes. A classic Canadian road movie comedy.', 0, 0),
('The Road to Wellville', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-28',
 '{"COMEDY","DRAMA"}', 'Alan Parker', 118, 'A story about the ins and outs of one unusual health facility in the early 20th century, run by the eccentric Dr. Kellogg.', 0, 0),
('The Puppet Masters', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-21',
 '{"HORROR","SCIFI","THRILLER"}', 'Stuart Orme', 109, 'The Earth is invaded by alien ''slugs'' that ride on people''s backs and control their minds.', 0, 0),
('Roomates', TIMESTAMP '2014-09-10', TIMESTAMP '1994-05-30',
 '{"DRAMA"}', 'Alan Metzger', 100, 'The story of a macho straight and a well-educated gay man who have to share an apartment at a half-way house for aids-patients. Slowly they become friends.', 0, 0),
('The Silences of the Palace', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-07',
 '{"DRAMA"}', 'Moufida Tlatli', 116, 'As she grows up, Alia (the daughter of housemaid Khedija) learns the secrets of the peaceful palace where she and her mother live.', 0, 0),
('Scorned', TIMESTAMP '2014-09-10', TIMESTAMP '1994-07-13',
 '{"DRAMA","THRILLER"}', 'Andrew Stevens', 100, 'A vengeful widow is out to seduce the relatives of the man she blames for her husband''s death.', 0, 0),
('The Scout', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-30',
 '{"COMEDY","DRAMA","SPORT"}', 'Michael Ritchie', 101, 'The story of a baseball scout who discovers a talented but troubled baseball player.', 0, 0),
('The Shadow', TIMESTAMP '2014-09-10', TIMESTAMP '1994-07-01',
 '{"ACTION","ADVENTURE","CRIME"}', 'Russell Mulcahy', 108, 'In 30''s New York City, the Shadow battles his nemesis, Shiwan Khan, who is building an atomic bomb.', 0, 0),
('The Shawshank Redemption', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-14',
 '{"CRIME","DRAMA"}', 'Frank Darabont', 142, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 0, 0),
('47 Ronin', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-22',
 '{"ACTION","DRAMA"}', 'Kon Ichikawa', 132, 'A group of disgraced samurai plan a decade long revenge against a corrupt lord.', 0, 0),
('Silent Fall', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-28',
 '{"DRAMA","MYSTERY","THRILLER"}', 'Bruce Beresford', 101, 'An autistic boy witnesses his parents'' double murder. Richard Dreyfuss as a controversial therapist, seeks to probe the child''s mind in order to solve the case.', 0, 0),
('A Simple Twist of Fate', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-02',
 '{"DRAMA","COMEDY"}', 'Gillies MacKinnon', 106, 'His life was emotionally closed off from the world, until an orphaned baby showed up at his house.', 0, 0),
('Slaughter of the Innocents', TIMESTAMP '2014-09-10', TIMESTAMP '1993-08-14',
 '{"CRIME","HORROR","MYSTERY"}', 'James Glickenhaus', 104, 'A seasoned FBI Agent''s child-genius son assists him on catching a child-killer, a schizophrenic mohab nut who believes he''s been chosen by god to be a new Noah.', 0, 0),
('Somebody to Love', TIMESTAMP '2014-09-10', TIMESTAMP '1996-09-27',
 '{"COMEDY","DRAMA"}', 'Alexandre Rockwell', 102, 'Mercedes is a taxi dancer who wants to be an actress. She''s involved with the married Harry, who considers himself a respected actor. Ernesto is in love with Mercedes, but he doesn''t dance or have money.', 0, 0),
('The Specialist', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-07',
 '{"ACTION","CRIME","DRAMA"}', 'Luis Llosa', 110, 'A woman entices a bomb expert she''s involved with into destroying the mafia that killed her family.', 0, 0),
('Speed', TIMESTAMP '2014-09-10', TIMESTAMP '1994-06-10',
 '{"ACTION","CRIME","THRILLER"}', 'Jan de Bont', 116, 'A young cop must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph.', 0, 0),
('In Spite of Love', TIMESTAMP '2014-09-10', TIMESTAMP '1994-04-09',
 '{"DRAMA","FAMILY"}', 'David Greene', 100, 'In 1970s New York, Martin (Maguire) hopes to locate his father and possibly reunite the parents who have been bitterly separated since he was born.', 0, 0),
('Squanto: A Warrior''s Tale', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-28',
 '{"ADVENTURE","BIOGRAPHY","DRAMA"}', 'Xavier Koller', 102, 'Historically inaccurate chronicle of Squanto''s life prior to and including the arrival of the ''Mayflower'' in 1620.', 0, 0),
('Star Trek: Generations', TIMESTAMP '2014-09-10', TIMESTAMP '1994-11-18',
 '{"ACTION","ADVENTURE","MYSTERY"}', 'David Carson', 118, 'Captain Picard, with the help of supposedly dead Captain Kirk, must stop a madman willing to murder on a planetary scale in order to enter an energy ribbon.', 0, 0),
('Stargate', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-28',
 '{"ACTION","ADVENTURE","SCIFI"}', 'Roland Emmerich', 121, 'An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.', 0, 0),
('Street Fighter', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-23',
 '{"ACTION","ADVENTURE","COMEDY"}', 'Steven E. de Souza', 102, 'Col. Guile and various other martial arts heroes fight against the tyranny of Dictator M. Bison and his cohorts.', 0, 0),
('The Sum of Us', TIMESTAMP '2014-09-10', TIMESTAMP '1995-03-08',
 '{"COMEDY","DRAMA"}', 'Geoff Burton', 100, 'A widowed father has to deal with two complex issues: while he is searching for ''Miss Right,'' his son, who is in his 20s and gay, is searching for ''Mr. Right.''', 0, 0),
('Teesra Kaun?', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-23',
 '{"COMEDY","DRAMA","THRILLER"}', 'Partho Ghosh', 160, 'Enroute via train to Bombay, one of three friends become a suspect in a homicide.', 0, 0),
('Terminal Velocity', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-23',
 '{"ACTION","COMEDY","MYSTERY"}', 'Deran Sarafian', 102, 'A maverick skydiver and a former KGB agent team up to stop the Russian mafia from stealing gold.', 0, 0),
('Heaven''s a Drag', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-02',
 '{"COMEDY","DRAMA","ROMANCE"}', 'Peter Mackenzie Litten', 101, 'A twenty-something drag queen dies of AIDS, but when his adoring ghost returns to the side of his surviving lover, he finds his lover doesn''t exactly miss him.', 0, 0),
('Tokarefu', TIMESTAMP '2014-09-10', TIMESTAMP '1994-03-05',
 '{"ACTION"}', 'Junji Sakamoto', 103, 'A school bus driver''s child is kidnapped and murdered. He then devotes his life to tracking down and killing the perpetrators using a gun that he happened to find under a vending machine.', 0, 0),
('Tollbooth', TIMESTAMP '2014-09-10', TIMESTAMP '1994-11-01',
 '{"ACTION","DRAMA","THRILLER"}', 'Salomé Breziner', 108, 'A tollbooth attendant''s fascination with a young woman who works at a gas station leads him into a love triangle and murder.', 0, 0),
('Trapped in Paradise', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-02',
 '{"ADVENTURE","COMEDY","CRIME"}', 'George Gallo', 111, 'Residents of a friendly Pennsylvania town foil three brothers'' plan to rob a bank on Christmas Eve.', 0, 0),
('Trial by Jury', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-09',
 '{"THRILLER","CRIME","DRAMA"}', 'Heywood Gould', 107, 'Valerie is a juror in the trail of a mob boss. When her young son''s life is threatened, she has no option other than to see that justice isn''t done.', 0, 0),
('True Lies', TIMESTAMP '2014-09-10', TIMESTAMP '1994-07-15',
 '{"ACTION","COMEDY","THRILLER"}', 'James Cameron', 141, 'A fearless, globe-trotting, terrorist-battling secret agent has his life turned upside down when he discovers his wife might be having an affair with a used car salesman.', 0, 0),
('The Legend of Drunken Master', TIMESTAMP '2014-09-10', TIMESTAMP '2000-10-20',
 '{"ACTION","COMEDY"}', 'Chia-Liang Liu', 102, 'A young martial artist is caught between respecting his pacifist father''s wishes or stopping a group of disrespectful foreigners from stealing precious artifacts.', 0, 0),
('Unveiled', TIMESTAMP '2014-09-10', TIMESTAMP '1994-08-03',
 '{"ACTION","DRAMA","THRILLER"}', 'William Cole', 103, 'An American woman uses herself as bait to help a CIA agent trap an alleged serial killer in Morroco.', 0, 0),
('Vanya on 42nd Street', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-19',
 '{"COMEDY","DRAMA","ROMANCE"}', 'Louis Malle', 119, 'New York actors rehearse Chekhov''s ''Uncle Vanya'' in a dilapidated theatre.', 0, 0),
('Wagons East', TIMESTAMP '2014-09-10', TIMESTAMP '1994-08-26',
 '{"ADVENTURE","COMEDY","WESTERN"}', 'Peter Markle', 107, 'In the 1860''s Wild West, when a ragged bunch of misfit settlers decide they cannot stand living in their current situation, they hire a grizzled cowboy to take them on a journey back to their hometowns east.', 0, 0),
('Warriors', TIMESTAMP '2014-09-10', TIMESTAMP '1995-07-06',
 '{"ACTION","DRAMA"}', 'Shimon Dotan', 101, 'A government-trained killing machine must turn his lethal skills against his top-secret squad''s AWOL leader', 0, 0),
('New Nightmare', TIMESTAMP '2014-09-10', TIMESTAMP '1994-10-14',
 '{"FANTASY","HORROR","MYSTERY"}', 'Wes Craven', 112, 'A demonic force has chosen Freddy Krueger as its portal to the real world. Can Heather play the part of Nancy one last time and trap the evil trying to enter our world?', 0, 0),
('When a Man Loves a Woman', TIMESTAMP '2014-09-10', TIMESTAMP '1994-05-13',
 '{"DRAMA","ROMANCE"}', 'Luis Mandoki', 126, 'An airline pilot and his wife are forced to face the consequences of her alcoholism when her addictions threaten her life and their daughter''s safety. While the woman enters detox, her husband must face the truth of his enabling behavior.', 0, 0),
('Where Are My Children?', TIMESTAMP '2014-09-10', TIMESTAMP '1994-09-18',
 '{"DRAMA"}', 'George Kaczender', 100, 'Based upon a true story, Marg Helgenberger stars as a single mother mysteriously arrested by the FBI and separated from her children, thus beginning a 25-year struggle to be reunited with them.', 0, 0),
('White Fang 2: Myth of the White Wolf', TIMESTAMP '2014-09-10', TIMESTAMP '1994-04-15',
 '{"ADVENTURE","FAMILY"}', 'Ken Olin', 106, 'In order to save one of the last Alaskin native tribes, Fang bands together with a friend of his master to stop miners from destroying a sacred land.', 0, 0),
('Witch Hunt', TIMESTAMP '2014-09-10', TIMESTAMP '1994-12-10',
 '{"CRIME","FANTASY","MYSTERY"}', 'Paul Schrader', 100, 'In a twisted 1950''s where everyone does magic, a private detective investigates a murder case without it.', 0, 0),
('With Honors', TIMESTAMP '2014-09-10', TIMESTAMP '1994-04-29',
 '{"COMEDY","DRAMA"}', 'Alek Keshishian', 103, 'Convinced his thesis will have him graduate with honors from Harvard University, a stuffy student finds himself at the mercy of a homeless man''s demands when he holds the papers hostage.', 0, 0),
('Wolf', TIMESTAMP '2014-09-10', TIMESTAMP '1994-06-17',
 '{"DRAMA","HORROR","ROMANCE"}', 'Mike Nichols', 125, 'Publisher Will Randall becomes a werewolf and has to fight to keep his job.', 0, 0),
('World War II: When Lions Roared', TIMESTAMP '2014-09-10', TIMESTAMP '1994-04-19',
 '{"DRAMA","HISTORY","WAR"}', 'Joseph Sargent', 194, 'This TV Movie is about the Tehran Conference between FDR, Winston Churchill, and Joseph Stalin. It shows the interaction between the three leaders at the close of the Second World War.', 0, 0),
('Wyatt Earp', TIMESTAMP '2014-09-10', TIMESTAMP '1994-06-24',
 '{"ACTION","ADVENTURE","BIOGRAPHY"}', 'Lawrence Kasdan', 191, 'Wyatt Earp is a movie about a man and his family. The movie shows us the good times and the bad times of one of the West''s most famous individuals.', 0, 0),
('XXX''s & OOO''s', TIMESTAMP '2014-09-10', TIMESTAMP '1994-06-21',
 '{"DRAMA","ROMANCE"}', 'Allan Arkush', 110, 'Four ex-wives become friends bonding through their shared experiences as ex-wives of country music singers.', 0, 0),
('In Between', TIMESTAMP '2014-09-10', TIMESTAMP '1994-01-06',
 '{"COMEDY","DRAMA","ROMANCE"}', 'Sylvia Chang', 105, 'Three roommates encounter trials and tribulations in their respective love lives.', 0, 0),
('Eat Drink Man Woman', TIMESTAMP '2014-09-10', TIMESTAMP '1994-08-03',
 '{"COMEDY","DRAMA","ROMANCE"}', 'Ang Lee', 124, 'A senior chef lives with his three grown daughters; the middle one finds her future plans affected by unexpected events and the life changes of the other household members.', 0, 0),
('Crusades', TIMESTAMP '2014-09-10', TIMESTAMP '1995-01-10',
 '{"DOCUMENTARY","HISTORY","WAR"}', 'Alan Ereira', 200, 'Terry Jones presents the history of the medieval religious wars in the middle-east known as the Crusades.', 0, 0),
('The Invaders', TIMESTAMP '2014-09-10', TIMESTAMP '1995-11-12',
 '{"SCIFI"}', 'Paul Shapiro', 148, 'The classic sci-fi series of the ''60s returns as one man, Scott Bakula, tries to stop an invasion of the earth by aliens disguised as humans.', 0, 0),
('Catherine the Great', TIMESTAMP '2014-09-10', TIMESTAMP '1996-04-28',
 '{"BIOGRAPHY","DRAMA","HISTORY"}', 'Marvin J. Chomsky', 100, 'Trapped in a loveless arranged marriage to the immature future Czar, a young German Princess proves a skillful political infighter and rises to become Catherine the Great.', 0, 0),
('Nothing Lasts Forever', TIMESTAMP '2014-09-10', TIMESTAMP '1995-11-05',
 '{"DRAMA","ROMANCE","THRILLER"}', 'Jack Bender', 155, 'Story of the personal lives and careers of three female doctors, from different backgrounds and walks of life, who work at a San Francisco county hospital.', 0, 0),
('Almost Golden: The Jessica Savitch Story', TIMESTAMP '2014-09-10', TIMESTAMP '1995-09-04',
 '{"BIOGRAPHY","DRAMA"}', 'Peter Werner', 120, 'The fact-based true story of the rapid rise to fame and untimely death of Jessica Savitch - one of America''s first female news anchors.', 0, 0),
('The American President', TIMESTAMP '2014-09-10', TIMESTAMP '1995-11-17',
 '{"COMEDY","DRAMA","ROMANCE"}', 'Rob Reiner', 114, 'Comedy-drama about a widowed U.S. president and a lobbyist who fall in love. It''s all above-board, but ''politics is perception'' and sparks fly anyway.', 0, 0),
('Amália - Uma Estranha Forma de Vida', TIMESTAMP '2014-09-10', TIMESTAMP '1995-07-01',
 '{"DOCUMENTARY"}', 'Bruno de Almeida', 285, 'A five hour documentary series about the legendary ''queen'' of fado.', 0, 0),
('Angels and Insects', TIMESTAMP '2014-09-10', TIMESTAMP '1996-01-26',
 '{"DRAMA","ROMANCE"}', 'Philip Haas', 116, 'In the 1800s a naturalist marries into a family of British aristocrats.', 0, 0),
('Antonia''s Line', TIMESTAMP '2014-09-10', TIMESTAMP '1996-02-02',
 '{"COMEDY","DRAMA"}', 'Marleen Gorris', 102, 'A Dutch matron establishes and, for several generations, oversees a close-knit, matriarchal community where feminism and liberalism thrive.', 0, 0),
('Antarctica', TIMESTAMP '2014-09-10', TIMESTAMP '1995-09-08',
 '{"DRAMA"}', 'Manuel Huerga', 106, 'A rock star falls in love with a common pickpocket without any personal history. But soon she finds herself in a contraband of drugs and both try to escape it.', 0, 0),
('Apollo 13', TIMESTAMP '2014-09-10', TIMESTAMP '1995-06-30',
 '{"ADVENTURE","DRAMA","HISTORY"}', 'Ron Howard', 140, 'NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.', 0, 0),
('Bad Boys', TIMESTAMP '2014-09-10', TIMESTAMP '1995-04-07',
 '{"ACTION","COMEDY","CRIME"}', 'Michael Bay', 118, 'Two hip detectives protect a murder witness while investigating a case of stolen heroin.', 0, 0),
('Batman Forever', TIMESTAMP '2014-09-10', TIMESTAMP '1995-06-16',
 '{"ACTION","ADVENTURE","FANTASY"}', 'Joel Schumacher', 121, 'Batman must battle Two-Face and The Riddler with help of an amourous psychologist and a young circus acrobat who becomes his sidekick, Robin.', 0, 0),
('Beach House', TIMESTAMP '2014-09-10', TIMESTAMP '1996-02-01',
 '{"COMEDY"}', 'Leigh Scott', 101, 'Three college Freshmen move in with a beautiful sorority girl when they can''t find on-campus housing.', 0, 0),
('Before Sunrise', TIMESTAMP '2014-09-10', TIMESTAMP '1995-01-29',
 '{"DRAMA","ROMANCE"}', 'Richard Linklater', 105, 'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.', 0, 0),
('Big Dreams & Broken Hearts: The Dottie West Story', TIMESTAMP '2014-09-10', TIMESTAMP '1995-01-22',
 '{"BIOGRAPHY","DRAMA","MUSIC"}', 'Bill D''Elia', 120, 'The autobiographical story of the life of country music legend Dottie West.', 0, 0),
('Mouth to Mouth', TIMESTAMP '2014-09-10', TIMESTAMP '1997-09-05',
 '{"COMEDY","ROMANCE"}', 'Manuel Gómez Pereira', 106, 'For financial reasons an unemployed aspiring actor works for a phone-sex enterprise. One day he receives a call from the mysterious wife of one of his best clients.', 0, 0),
('Body Language', TIMESTAMP '2014-09-10', TIMESTAMP '1995-07-22',
 '{"CRIME","THRILLER"}', 'George Case', 120, 'A lawyer, defending a Mafia boss, falls for a beautiful woman with a sad story to tell. She says she''s being abused by her brutal husband and she needs his help.', 0, 0),
('Bombay', TIMESTAMP '2014-09-10', TIMESTAMP '1998-07-25',
 '{"DRAMA","MUSICAL","ROMANCE"}', 'Mani Ratnam', 130, 'A Hindu man and a Muslim woman fall in love in a small village and move to Mumbai, where the have two children. However, growing religious tensions and erupting riots threaten to tear the family apart.', 0, 0),
('Braveheart', TIMESTAMP '2014-09-10', TIMESTAMP '1995-05-24',
 '{"BIOGRAPHY","DRAMA","HISTORY"}', 'Mel Gibson', 178, 'When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.', 0, 0)