package ar.edu.itba.paw.g4.model.builder;

import org.joda.time.DateTime;

import ar.edu.itba.paw.g4.model.EmailAddress;
import ar.edu.itba.paw.g4.model.User;

/**
 * Autogenerated POJO Fluent Builder
 */
// @Generated("PojoBuilder")
public class UserBuilder implements Cloneable {
	protected UserBuilder self;
	protected String value$firstName$java$lang$String;
	protected boolean isSet$firstName$java$lang$String;
	protected String value$lastName$java$lang$String;
	protected boolean isSet$lastName$java$lang$String;
	protected EmailAddress value$email$ar$edu$itba$paw$g4$model$EmailAddress;
	protected boolean isSet$email$ar$edu$itba$paw$g4$model$EmailAddress;
	protected String value$password$java$lang$String;
	protected boolean isSet$password$java$lang$String;
	protected DateTime value$birthDate$org$joda$time$DateTime;
	protected boolean isSet$birthDate$org$joda$time$DateTime;
	protected Integer value$id$java$lang$Integer;
	protected boolean isSet$id$java$lang$Integer;

	/**
	 * Creates a new {@link UserBuilder}.
	 */
	public UserBuilder() {
		self = (UserBuilder) this;
	}

	/**
	 * Sets the default value for the {@link User#firstName} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withFirstName(String value) {
		this.value$firstName$java$lang$String = value;
		this.isSet$firstName$java$lang$String = true;
		return self;
	}

	/**
	 * Sets the default value for the {@link User#lastName} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withLastName(String value) {
		this.value$lastName$java$lang$String = value;
		this.isSet$lastName$java$lang$String = true;
		return self;
	}

	/**
	 * Sets the default value for the {@link User#email} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withEmail(EmailAddress value) {
		this.value$email$ar$edu$itba$paw$g4$model$EmailAddress = value;
		this.isSet$email$ar$edu$itba$paw$g4$model$EmailAddress = true;
		return self;
	}

	/**
	 * Sets the default value for the {@link User#password} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withPassword(String value) {
		this.value$password$java$lang$String = value;
		this.isSet$password$java$lang$String = true;
		return self;
	}

	/**
	 * Sets the default value for the {@link User#birthDate} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withBirthDate(DateTime value) {
		this.value$birthDate$org$joda$time$DateTime = value;
		this.isSet$birthDate$org$joda$time$DateTime = true;
		return self;
	}

	/**
	 * Sets the default value for the {@link User#id} property.
	 *
	 * @param value
	 *            the default value
	 * @return this builder
	 */
	public UserBuilder withId(Integer value) {
		this.value$id$java$lang$Integer = value;
		this.isSet$id$java$lang$Integer = true;
		return self;
	}

	/**
	 * Returns a clone of this builder.
	 *
	 * @return the clone
	 */
	@Override
	public Object clone() {
		try {
			UserBuilder result = (UserBuilder) super.clone();
			result.self = result;
			return result;
		} catch (CloneNotSupportedException e) {
			throw new InternalError(e.getMessage());
		}
	}

	/**
	 * Returns a clone of this builder.
	 *
	 * @return the clone
	 */
	public UserBuilder but() {
		return (UserBuilder) clone();
	}

	/**
	 * Creates a new {@link User} based on this builder's settings.
	 *
	 * @return the created User
	 */
	public User build() {
		try {
			User result = new User(value$firstName$java$lang$String,
					value$lastName$java$lang$String,
					value$email$ar$edu$itba$paw$g4$model$EmailAddress,
					value$password$java$lang$String,
					value$birthDate$org$joda$time$DateTime);
			if (isSet$id$java$lang$Integer) {
				result.setId(value$id$java$lang$Integer);
			}
			return result;
		} catch (RuntimeException ex) {
			throw ex;
		} catch (Throwable t) {
			throw new java.lang.reflect.UndeclaredThrowableException(t);
		}
	}
}
